name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "**"
      - "!.github/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Context
        run: |
          echo "repo=$GITHUB_REPOSITORY"
          echo "ref=$GITHUB_REF (event=$GITHUB_EVENT_NAME)"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.DEPLOY_ROLE_ARN }}
          aws-region: us-east-1

      - name: WhoAmI (STS)
        run: aws sts get-caller-identity

      - name: Echo targets
        run: |
          echo "Bucket=${{ vars.DEPLOY_BUCKET }}"
          echo "CF_DIST_ID=${{ vars.CF_DIST_ID }}"

      - name: Sync to S3
        run: aws s3 sync dist s3://${{ vars.DEPLOY_BUCKET }}/ --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CF_DIST_ID }} --paths "/*"
